on: push
name: check
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: docker://node:10.15.3
      with:
        args: npm install
    - name: test
      uses: docker://node:10.15.3
      with:
        args: npm test
